remote_theme: the-256-foundation/hacker-theme
title: Hydra Pool
description: Open Source Bitcoin Mining Pool
github: https://github.com/256-Foundation/Hydra-Pool
  repository_url: https://github.com/The-256-Foundation/Hydra-Pool
  owner_url: https://256foundation.org
